title: Dottor Sorriso
baseurl: ""
url: "https://cialdecompatibili-netizen.github.io"
email:
description: >-
  Il dentista più pazzo di Roma. Cure serie, risate garantite.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
exclude:
  - vendor
  - docs

permalink: /:categories/:title/

timezone:

include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Dottor Sorriso"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Dentista romano, un po' fuori di testa. Ti tolgo il dente e ti faccio ridere."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
